server:
  port: 8800

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: jwt, oauth2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umbrella
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    show-sql: true
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false


logging:
  level:
    org.hibernate.type: trace